DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE(EMP_ID INT PRIMARY KEY,
					  EMP_FNAME VARCHAR(20) NOT NULL,
                      EMP_LNAME VARCHAR(20),
                      DEPARTMENT VARCHAR(10) NOT NULL,
                      SALARY INT DEFAULT 20000 NOT NULL,
                      EMAIL VARCHAR(30));
			
INSERT INTO EMPLOYEE
VALUES(1001,"Alex","D","Testing",25000,"alex@company.com");
INSERT INTO EMPLOYEE
VALUES(1002,"Celin","K","Account",16500,"celine@company.com");
INSERT INTO EMPLOYEE
VALUES(1003,"John","L","SDE",45000,"john@company.com");
INSERT INTO EMPLOYEE
VALUES(1004,"Selena","G","Marketing",22500,"selena@company.com");
INSERT INTO EMPLOYEE
VALUES(1005,"Enrique","I","IT",35000,"enrique@company.com");
INSERT INTO EMPLOYEE
VALUES(1006,"Robin","P","IT",35000,"robin@company.com");
INSERT INTO EMPLOYEE
VALUES(1007,"STALIN","C","NETWORKING",45000,"stalin@company.com");
SELECT
*,
IF(SALARY>30000,"SENIOR",
IF(SALARY>20000 AND SALARY<30000,"MID-SENIOR","JUNIOR")) AS GRADE 
FROM
EMPLOYEE;