USE college;
DROP TABLE IF EXISTS SANDBOX_DEPARTMENT,SANDBOX_TEACHER;
CREATE TABLE SANDBOX_DEPARTMENT(
DEPT_ID VARCHAR(10) PRIMARY KEY,
DEPT_NAME VARCHAR(60));

CREATE TABLE SANDBOX_TEACHER(
TEACHER_ID VARCHAR(10) PRIMARY KEY,
TEACHER_NAME VARCHAR(60),
DEPT_ID VARCHAR(10));

INSERT INTO SANDBOX_DEPARTMENT VALUES('D1','COMPUTER');
INSERT INTO SANDBOX_TEACHER VALUES('T1','BHUSHAN','D1');

INSERT INTO SANDBOX_TEACHER VALUES('T2','GHOST','D999');

SELECT * FROM SANDBOX_DEPARTMENT;
SELECT * FROM SANDBOX_TEACHER;

ALTER TABLE SANDBOX_TEACHER
ADD CONSTRAINT FK_DEPT FOREIGN KEY (DEPT_ID) REFERENCES SANDBOX_DEPARTMENT(DEPT_ID);

