USE COLLEGE;
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    DEPT VARCHAR(20),
    SALARY INT
);

INSERT INTO EMPLOYEE VALUES
(1,'Amit','HR',50000),
(2,'Priya','IT',60000),
(3,'Rahul','Finance',55000),
(4,'Sneha','IT',70000),
(5,'Karan','HR',50000),
(6,'Pooja','Finance',65000),
(7,'Rohan','IT',60000),
(8,'Neha','Marketing',45000),
(9,'Arjun','Marketing',50000),
(10,'Meera','HR',70000),
(11,'Vikas','Finance',65000),
(12,'Anjali','IT',80000),
(13,'Deepak','Marketing',55000),
(14,'Ritu','HR',60000),
(15,'Manish','Finance',50000),
(16,'Kavya','IT',70000),
(17,'Suresh','Marketing',45000),
(18,'Nikita','HR',60000),
(19,'Ajay','Finance',80000),
(20,'Simran','IT',50000);

SELECT ID, NAME, DEPT, SALARY,
RANK() OVER(ORDER BY SALARY DESC) AS RANK_NO
FROM EMPLOYEE;

SELECT ID, NAME, DEPT, SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK_NO
FROM EMPLOYEE;

SELECT ID, NAME, DEPT, SALARY,
ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROW_NO
FROM EMPLOYEE;

SELECT ID,
NAME,
DEPT,
SALARY,
DENSE_RANK() OVER(PARTITION BY DEPT ORDER BY SALARY DESC) AS DEPT_RANK_NO
FROM EMPLOYEE;


SELECT ID,
NAME,
DEPT,
SALARY,
SUM(SALARY) OVER(PARTITION BY DEPT ORDER BY SALARY DESC) AS DEPT_RANK_NO
FROM EMPLOYEE;



SELECT ID,
NAME,
DEPT,
SALARY,
MAX(SALARY) OVER(PARTITION BY DEPT ORDER BY SALARY) AS DEPT_RANK_NO
FROM EMPLOYEE;



SELECT ID,
NAME,
DEPT,
SALARY,
MIN(SALARY) OVER(PARTITION BY DEPT ORDER BY SALARY) AS DEPT_RANK_NO
FROM EMPLOYEE;


SELECT ID,
NAME,
DEPT,
SALARY,
AVG(SALARY) OVER (PARTITION BY DEPT) AS AVG_SALARY,
SALARY-AVG(SALARY)OVER(PARTITION BY DEPT) AS DIFF
FROM EMPLOYEE;


SELECT ID,
NAME,
DEPT,
SALARY,
AVG(SALARY) OVER (PARTITION BY DEPT) AS AVG_SALARY
FROM EMPLOYEE;
